name: hexfetch-ui

on:
  push:
    branches:
      - main
  release:
    types: [created]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'

    - name: Init
      run: |
        go mod init hexfetch-ui
        go mod tidy
        
    - name: Build
      run: go build -o hexfetch-ui -v ./...
    
    - name: Upload to GitHub Release
      if: github.event_name == 'release'
      uses: softprops/action-gh-release@v2
      with:
        files: hexfetch-ui
      
