name: hexfetch-ui

on:
  push:
    branches:
      - main
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libgl1-mesa-dev libx11-dev libxcursor-dev libxrandr-dev libxinerama-dev libxi-dev libxxf86vm-dev pkg-config

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24.2'

    - name: Install fyne-cross
      run: |
        go install github.com/fyne-io/fyne-cross@latest

    - name: Build AppImage
      run: |
        go mod edit -go=1.24
        go mod edit -require fyne.io/fyne/v2@v2.4.5
        go mod tidy
        fyne-cross linux -arch=amd64 -icon icon.png -name "Hexfetch UI" -app-id com.hexfetch.ui -image golang:1.24
        mv ./fyne-cross/dist/linux-amd64/*.AppImage hexfetch.AppImage

    - name: Upload hexfetch-ui AppImage as artifact
      uses: actions/upload-artifact@v4
      with:
        name: hexfetch-appimage
        path: hexfetch.AppImage

    - name: Upload to GitHub Release
      if: github.event_name == 'release'
      uses: softprops/action-gh-release@v2
      with:
        files: hexfetch.AppImage
        draft: true
